### ISSUE TITLE
HelpingMapper.swift: Invalid redeclaration of '<--' which differs only by the kind of optional passed as an inout argument ('Transform.Object!' vs. 'Transform.Object?')

### ISSUE THREAD

**Issue by shroff-kandarp** [sacOO7/socketcluster-client-swift#14]
Xcode gives redeclaration warnings.

Invalid redeclaration of '<--' which differs only by the kind of optional passed as an inout argument ('Transform.Object!' vs. 'Transform.Object?')

**Comment by sacOO7** [comment]
Hi @shroff-kandarp , is it causing any problem for now?

**Comment by sacOO7** [comment]
Ok sure, will look into it. Also, let me know if you are facing any issues with current client.

**Comment by sacOO7** [comment]
Hi @shroff-kandarp , i have updates library to support swift 4.2. Try to update it. Let me know if you face any issues :)
