### ISSUE TITLE
Please update 'HandyJson' Version Due to Swift 4.2 

### ISSUE THREAD

**Issue by vishalcnz** [sacOO7/socketcluster-client-swift#15]

**Comment by sacOO7** [comment]
Hi @vishalcnz , are you facing any problem with current library?

**Comment by vishalcnz** [comment]
Yes in swift 4.2 is showing errors

**Comment by sacOO7** [comment]
Hi @vishalcnz , I tried updating the HandyJson dependency to 4.2.0. But, it is generating some weird error. I have created error for the same here https://github.com/alibaba/HandyJSON/issues/294. Updating the dependency might lose compatibility with previous versions. I cannot update the dependency till issue is resolved.

**Comment by sacOO7** [comment]
Also it will be helpful if you can post here, the error being generated due to swift 4.2

**Comment by sacOO7** [comment]
I will recommend you cloning the code instead... include the source code of scclient inside your code. Download library dependencies separately with your required versions.

**Comment by keisyrzk** [comment]
I wonder why you use extra conversion for the json. If we get the json from sockets than it is easier to handle it directly on our own. HandyJSON usage cuts the first son header.

**Comment by sacOO7** [comment]
Hi @vishalcnz I have updated HandyJson to latest version. It will be good if you can download it using SPM. Currently it's not available on cocoapod due to internet issues. Also you can directly import this code as module in your project.

**Comment by sacOO7** [comment]
Hi @vishalcnz , can you install latest version of pod.... I believe the fix is now available on cocoapods....
