### ISSUE TITLE
Not Connecting 

### ISSUE THREAD

**Issue by vishalcnz** [sacOO7/socketcluster-client-swift#32]
Hello 

I tried to change my server URL and every time i try to connect to our server it show me below error. And i tried our new server URL on web and Android and it's working fine. 

`Invalid HTTP upgrade ` code 404

I found you use `Starscream 3.1.1` but latest version is `4.0.4`

Is this issue because of that ? Looking forward for your help

Thanks
Vishal

**Comment by sacOO7** [comment]
Ok, I will look into the issue and get back to you.  Will you be able to
provide me with logs?

**Comment by vishalcnz** [comment]
Hello @sacOO7 thanks for your reply. Here is the log

```
▿ Optional<Error>
  ▿ some : WSError
    - type : Starscream.ErrorType.upgradeError
    - message : "Invalid HTTP upgrade"
    - code : 403
```

**Comment by vishalcnz** [comment]
Hello @sacOO7 I figure out the problem. It's something wrong on our side. Sorry i just find the issue.
