### ISSUE TITLE
How to use in objective-c

### ISSUE THREAD

**Issue by vishalcnz** [sacOO7/socketcluster-client-swift#6]
Hello 

I am trying to use SocketClusteriOS but i found it's very old can not connect to my server. 

My question is how can i use this lib to objective-c code ?

Thanks
Vishal

**Comment by sacOO7** [comment]
Hi @vishalcnz , I think you can use swift code which is compatible with objective c. It is better if you can create a project compatible with both objective c and swift. You can find lot of tutorials describing for the same.

**Comment by sacOO7** [comment]
Hi @vishalcnz , if you have any updates on this, please post here.... Otherwise I will close the issue.

**Comment by vishalcnz** [comment]
Hello @sacOO7 yes i found the solution i create a code which is compatible with both objective-c and swift. Thanks for your help
