### ISSUE TITLE
Update HandyJSON pod dependency

### ISSUE THREAD

**Issue by CeMcK** [sacOO7/socketcluster-client-swift#7]
Hi could you please update the pod dependencies so that we can use the newest version of HandyJSON to work with swift 4.1
Thanks

**Comment by sacOO7** [comment]
Hi @CeMcK , I can update it to match latest version. Is there any problem you are facing right now? I would like to know about it. I am sure the current library should work in both swift 3.x and 4.x

**Comment by CeMcK** [comment]
@sacOO7 Thanks that would be great! Yes there are build errors. Also HandyJSON docs says for swift 4 you should use the newest version

**Comment by sacOO7** [comment]
Hi @CeMcK , will be updating the library with latest HandyJson and publishing the latest version soon enough 👍

**Comment by sacOO7** [comment]
Hi @CeMcK, I have published library with latest version of HandyJson. Please let me know if that works for you 👍

**Comment by CeMcK** [comment]
yes you can close it. Thanks 👍

**Comment by sacOO7** [comment]
I also want to know your feedback about library. Let me know if it's
working for you. I am also open to new suggestions 😌✌️

**Comment by CeMcK** [comment]
Sorry I don't have time to test it now. I am going to look into this later this week 👍
Yes I'm developing for iOS

**Comment by sacOO7** [comment]
Ok sure @CeMcK , Please let me know once you test it 👍

**Comment by CeMcK** [comment]
Yes it is working. Thanks  👍

**Comment by sacOO7** [comment]
Hi @CeMcK , thanks for your help. I am really grateful :+1: . If you have free time, can you write a blog to demonstrate use of library in iOS application? It can be something like this https://medium.com/@sachinshinde7676/building-a-chat-app-for-android-using-socketcluster-in-node-js-90a4ae6c3577. Since you are an iOS dev, it should not take much time. It will also be useful for other iOS devs.... Thanks again !!!!

**Comment by CeMcK** [comment]
No problem! Yes I will look into doing this if I find free time 👍

**Comment by sacOO7** [comment]
So, I will be closing this issue.... Please let me know if you need any help on above :+1:
